[project]
name = "ay-gogh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "cefrpy>=1.0.1",
    "pip>=25.3",
    "python-fasthtml>=0.12.30",
    "readtime>=3.0.0",
    "setuptools>=80.9.0",
    "spacy>=3.8.7",
    "textstat>=0.7.10",
    "tqdm>=4.67.1",
    "wheel>=0.45.1",
]

[tool.ruff.lint]
ignore = ["F403", "F405"]
