[project]
name = "ay-gogh"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "python-frontmatter>=1.1.0",
    "starhtml>=0.5.9",
]

[tool.ruff.lint]
ignore = ["F403", "F405"]

[dependency-groups]
dev = [
    "ruff>=0.15.2",
    "ty>=0.0.18",
]
